# Sysmon Monitoring

## Objective

Deploy Sysmon to improve endpoint visibility and gain experience analyzing security-relevant Windows events generated during offensive security testing.

## Environment

### Monitoring Host

* Windows 10 Pro
* Domain Joined Workstation
* Active Directory Environment

### Security Tools

* Sysmon
* Event Viewer
* Kali Linux
* Chainsaw

## Overview

Sysmon provides detailed endpoint telemetry that is not available through standard Windows logging alone.

The goal of this project was to capture and analyze activity generated by common attacker techniques in a controlled lab environment.

## Sysmon Deployment

Installed Sysmon on the Windows workstation and verified successful operation.

Verified:

* Sysmon Service Running
* Event Collection Active
* Logs Available in Event Viewer

Location:

Applications and Services Logs

Microsoft

Windows

Sysmon

Operational

## Monitoring Activities

The following activities were performed from Kali Linux against lab systems:

### Network Scanning

Executed Nmap scans to identify exposed services.

Observed Sysmon network connection events generated during scanning activity.

### Remote Service Enumeration

Performed SMB enumeration against vulnerable targets.

Reviewed corresponding network activity and process execution logs.

### Lab Validation

Verified that security-relevant activity generated observable telemetry that could later be used for detection engineering and incident investigation.

## Important Sysmon Events

### Event ID 1

Process Creation

Useful for tracking:

* Command execution
* PowerShell activity
* Administrative actions
* Malware execution

### Event ID 3

Network Connection

Useful for identifying:

* Port scanning
* Lateral movement
* External communications
* Command and Control traffic

### Event ID 11

File Creation

Useful for identifying:

* Malware drops
* Tool deployment
* Suspicious file activity

## Detection Workflow

Lab Activity

↓

Sysmon Event Generation

↓

Event Viewer Analysis

↓

EVTX Export

↓

Chainsaw Analysis

↓

Detection Validation

## Skills Demonstrated

* Endpoint Monitoring
* Windows Logging
* Security Telemetry Analysis
* Event Investigation
* Detection Engineering Fundamentals
* Defensive Security Operations

## Lessons Learned

Effective detection begins with high-quality telemetry. Sysmon provides detailed visibility into system activity and serves as a valuable data source for threat detection and incident response.

The project also reinforced the importance of understanding both attacker behavior and defensive monitoring techniques.

## Future Enhancements

* Sigma Rule Integration
* Chainsaw Detection Testing
* Security Onion Integration
* Wazuh Integration
* Custom Detection Development
* Active Directory Attack Detection

## Screenshots

Include:

* Sysmon Installation
* Event Viewer Sysmon Logs
* Event ID 1 Examples
* Event ID 3 Examples
* Exported EVTX Logs
* Chainsaw Analysis Results
